### ISSUE TITLE
Tests Of Command Strings With Args Fail On Windows

### ISSUE THREAD

**Issue by XedinUnknown** [adambrett/php-shell-wrapper#12]
Hi,

I'm trying to run the unit tests for your library here. However, I'm having some difficulty, as many of them fail, like so:
```
1) AdamBrett\ShellWrapper\Tests\CommandTest::testCanAddArgument
Command should have arguments
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'ls --test 'value''
+'ls --test "value"'
```

This is because the [`escapeshellargs()`](http://php.net/manual/en/function.escapeshellarg.php) function you [use on argument values](https://github.com/adambrett/php-shell-wrapper/blob/master/src/Command/Value.php#L37) escapes them differently on Windows. Particularly, it surrounds the values with double quotes instead of single.

Also, I've had trouble running tests at all, since the bootstrap seems to [require](https://github.com/adambrett/php-shell-wrapper/blob/master/tests/bootstrap.php#L3) an `autoload.php` file in a rather strange location. Temporarily got around this by modifying the required path.

**Comment by adambrett** [comment]
Hi @XedinUnknown 

Thanks for reporting the issue, unfortunately I don't develop on windows, and haven't for around 15 years. I don't currently have access to a windows machine, so have no way of testing this.

I would be apprehensive of changing the tests as travis-ci doesn't currently support windows, so I'd have no way of ensuring continuity going forward, were I to add windows support to the tests.

The location of autoload.php is the standard composer path (project root/vendor/autoload.php), unless it installs somewhere different/weird on windows.

Sorry it's not better news, the library _should_ work on windows unchanged, but for now I'm going to consider _development_ on windows unsupported.

**Comment by XedinUnknown** [comment]
Yes, the library seems to work. I'll see what I can do WRT the test, so that they work on both Win and Nix.

WRT autoloader path. If the project root is `/myproject`, and Composer dependencies are in `/myproject/vendor`, and so the lib is in `/myproject/vendor/adambrett/php-shell-wrapper` and the tests are in `/myproject/vendor/adambrett/php-shell-wrapper/tests`, then the bootstrap will look in `/myproject/vendor/adambrett/php-shell-wrapper/vendor/autoload.php`.
On the other hand, if testing the project on its own, then not sure why there would be a `../vendor/autoload.php`.

**Comment by adambrett** [comment]
Ah, ok, I develop the library in isolation, not the context of an application, so the autoloader lives in "tests/../vendor/autoload.php", the library does not include an autoloader of its own, instead relying on composer's, and the tests aren't expected to be run from the context of a project.

**Comment by XedinUnknown** [comment]
Understood. So, would I just have to run `composer dump-autoload` presumably. Thanks!
