### ISSUE TITLE
Pipeline one command to another

### ISSUE THREAD

**Issue by garex** [adambrett/php-shell-wrapper#17]
Hi Adam!

Do you have anything that will connect output of one command to input of another?

Something like pipeline in bash?

`echo 123 | grep 2 | cat`

Or can you suggest how to better extend your lib to add such thing?

**Comment by adambrett** [comment]
Hi @garex 

You should probably take a look at the Commands Collection class: https://github.com/adambrett/php-shell-wrapper/blob/master/src/Command/Collections/Command.php

You could either fork the library and add a "C_PIPE" constant, or sub-class that collection and modify it that way. It would also work if you just pass a literal pipe character to the `$type` param in the constructor.

If you did decide to fork and add a C_PIPE constant, a pull request would be very welcome, just be mindful of test coverage and PSR-2 requirements!

Thanks

**Comment by garex** [comment]
Adam, how then user will be able to understand which command failed?

For example I have two commands: `cmd1 | cmd2`.

And they have similar error messages, that are similar.

How then it would be possible to get?

**Comment by adambrett** [comment]
You can't do that with pipes unfortunately, which is a bash/shell thing, and not related to this library nor PHP. If the error messages are similar, there's just no way to tell.

When you use a pipe, all of the piped commands are run immediately and in parallel, with the output from each being passed in to the next.

There are workarounds that involve more complex bash scripts, but that is outside of the scope of this library.

The easiest "workaround" using bash would be to create a wrapper for one of the Runners, then ensure that the last "Command" in your pipe is always:

```bash
&& printf '%s\n' "${PIPESTATUS[@]}"
```

Then the last `x` lines of your output would be the exit statuses of each command, you could then parse this out and return it in a "getPipeStatus" method (or similar), and ignore it in the `getOutput` methods.

This is not POSIX compliant however, and will likely break on any shell that isn't bash.

It would look something like this (extremely untested):

```php
<?php

namespace YourApp\ShellWrapper\Runners;

use AdamBrett\ShellWrapper\Command\CommandInterface;
use AdamBrett\ShellWrapper\Command\Builder;
use AdamBrett\ShellWrapper\Runners\Exec;

class PipeExec extends Exec
{
    protected $pipeStatus;
    protected $lastCommand;
    
    public function run(CommandInterface $command)
    {
        $this->lastCommand = $command;
        
        $return = parent::run($this->getPipeStatusCommand($command));

        $numCommands = substr_count($command, '|') + 1;
        
        $this->pipeStatus = array_slice($this->output, ($numCommands * -1), $numCommands);
        $this->output = array_slice($this->output, 0, ($numCommands * -1));
        $this->returnValue = $this->pipeStatus[($numCommands - 1)];
        
        return $return;
    }

    public function commandDidFail()
    {
        foreach ($this->pipeStatus as $status) {
            if ($status !== 0) {
                return true;
            }
        }

        return false;
    }

    public function getFailedCommand()
    {
        foreach ($this->pipeStatus as $index => $status) {
            if ($status !== 0) {
              break;
            }
        }

        $commands = explode('|', $this->lastCommand);

        return trim($commands[$index]);
    }

    private function getPipeStatusCommand($command)
    {
        $pipeStatus = new Builder('printf');
        $pipeStatus->addParam("'%s\n'")
          ->addParam('"${PIPESTATUS[@]}"');

        return sprintf(
          '%s && %s',
          $command,
          $pipeStatus
        );
    }
}
```

Usage:

```php
$ls = new Command('ls');
$grep = new Builder('grep');
$grep->addParam('foo');

$commands = new Collection\Command([$ls, $grep], Collection\Command::C_PIPE);

$exec = new PipeExec();
$exec->run($commands);

if ($exec->commandDidFail()) {
    echo $exec->getFailedCommand();
}
```

**Comment by garex** [comment]
Yes, as I see at http://stackoverflow.com/a/9168523/388929

> This is bashish

But what if pipe inside PHP?

Something like this but in more better way: https://gist.github.com/garex/609d37583637f72c1233b9ed45061b61

**Comment by adambrett** [comment]
It shouldn't make a difference that it's in PHP. Have a play with the example I gave you above. I can't guarantee that it will work, but it should start you off in the right direction.
