### ISSUE TITLE
Another way to add several arguments with the same names

### ISSUE THREAD

**Issue by Bukharovsi** [adambrett/php-shell-wrapper#23]
I found a solution to add multiple arguments with the same name.
`$arg = new Argument($name, [$val1, $val2]);`
But there is too hard to find out this approach without reading documentation. There is no apparent that second argument must be an array. 

Let me show another possible way:
```
$cmd = new Command(‘docker build’);
$cmd->addArgument(new Argument(‘tag’, ‘latest’);
$cmd->addArgument(new Argument(‘tag, ‘3.5.0’);
```
The typical way to use multiple arguments are loops. Let me add some example

**First way**

```
$cmd = new Command(‘docker build’);
foreach($tags as $tag) {
   $cmd->addArgument(new Argument(‘tag’, $tag->getVersion());
}
```

**Second way**

```
$cmd = new Command(‘docker build’);
$attr = [];
foreach($tags as $tag) {
   $attr[] = $tag->getVersion();
}
$cmd->addArgument(new Argument(‘tag’, $arrt);
```

in my opinion In this case the first way is more object oriented. In another case second way is preferable. Because i suggest add another way for multiple attributes and save “old” way.

**How we can fix this?**
As easy as ABC
`ArgumentCollection` file now:

```   
public function addArgument(Argument $argument)
{
     $this->arguments[$argument->getName()] = $argument;
}
```

I suggest replace it to something like this: 

```    
public function addArgument(Argument $argument)
{
    $this->arguments[md5((string) $argument] = $argument;
}
```
Also it will need to fix some unit-tests.

Will you approve this proposal? If yes i will create merge request.
Thanks a lot!

**Comment by Bukharovsi** [comment]
Hmm, may be we must save this test
```
    public function testDuplicateArguments()
    {
        $argumentList = new ArgumentList();
        $argumentList->addArgument(new Argument('test', 'value'));
        $argumentList->addArgument(new Argument('test', 'value'));
        $this->assertEquals("--test 'value'", (string) $argumentList, 'ArgumentList should remove duplicates');
    }
```

and method must looks like
```
public function addArgument(Argument $argument)
{
    $this->arguments[md5((string) $argument)] = $argument;
}
```

**Comment by adambrett** [comment]
This is intended behaviour - it allows you to overwrite an argument by re-adding it.

If you want to change this behaviour, I would recommend extending the CommandBuilder and using it to keep track of arguments, this is the "Open-Closed Principle" something like this:

```
<?php

namespace App\Command;

use AdamBrett\ShellWrapper\Command\Builder;

class MyBuilder extends Builder
{
    protected $arguments = [];

    public function addArgument($name, $value = null)
    {
        if (!is_array($value)) {
            $value = [$value]
        }

        $this->arguments[$name] = array_merge($this->arguments[$name], $value)

        $this->command->addArgument(new Argument($name, $this->arguments[$name]));

        return $this;
    }
}
```

Hope this helps

Thanks
