### ISSUE TITLE
Acquire Exit Code

### ISSUE THREAD

**Issue by XedinUnknown** [adambrett/php-shell-wrapper#7]
Hi,

Is it possible to get the exit code of the executed command?

I know it's hard, I tried it myself, and there didn't seem to be a *reliable* way to do that. But [php-shellcommand](https://github.com/mikehaertl/php-shellcommand) seems to have solved this problem somehow.

**Comment by adambrett** [comment]
@XedinUnknown: The `getReturnValue` method on the `Exec`, `ShellExec`, and `System` Runners should give you that.

Let me know if that doesn't solve your problem and I'll re-open the issue and look in to it!

**Comment by XedinUnknown** [comment]
Hi!

Since I filed the issue, I had a chance to look at the code, which I really
like by the way.

However, what I really need is to be able to get the return value, and the
output: from both standard outputs! I understand that this can only be done
using `proc_open()`. Therefore, I am preparing a pull request with a `Proc`
runner. Hopefully will be ready this week.

**Comment by adambrett** [comment]
@XedinUnknown thanks, a Proc runner is something I overlooked when I originally wrote this and a few people have asked for it, so a PR for that would be great :)

I'll keep an eye out for it!

**Comment by XedinUnknown** [comment]
Very sorry for that pull request I never filed. I've already got a working prototype, and now normalizing the logic and creating unit tests.

One of the problems I had was with the Composer dependency type `path`, which was buggy. Another problem was with getting PHPUnit to run on my Windows setup. Now that most of these issues are rectified, I should be filing the PR this weekend, or next week.
