### ISSUE TITLE
Builder supports only one argument per each name

### ISSUE THREAD

**Issue by cvuorinen** [adambrett/php-shell-wrapper#8]
The Arguments collection stores the arguments in an associative array where the argument name is the key. This causes that if I try to set a second argument with a name that has already been set, the first argument value will be overridden by the second.

Any reason why only one argument per each name can be added? Or is there a way to set multiple arguments with the same name in the current implementation?

I think there are many cases when you need to add multiple arguments with the same name, for example:
```
rsync -avz --exclude '.git*' --exclude 'cache' source/ destination/
```
```
curl --header 'Accept-Charset: utf-8' --header 'Content-Type: application/x-www-form-urlencoded' http://www.domain.com
```
```
raspistill --output 'image.jpg' --exif 'IFD0.Artist=Boris' --exif 'GPS.GPSAltitude=1235/10'
```

**Comment by adambrett** [comment]
Hi @cvuorinen, this was an oversight on my part when writing the first version of the library. I've had a thought about the best way to handle this, check out the pull request in #9 and let me know if that suits your needs.

Thanks

**Comment by cvuorinen** [comment]
Hi. Good to know you have already been working on this. The pull request does indeed address this issue and it would work in my use case as I have the argument values in an array.

That implementation however would still override the previously set value(s) if you would call `AdamBrett\ShellWrapper\Command\Builder::addArgument` multiple times with the same name. Don't know if that is a problem or if it would make more sense to handle that differently. For example check in `AdamBrett\ShellWrapper\Command\Collections\Arguments::addArgument` if there already exists an argument with the same name and then merge the new value with the existing one into an array or something like that.

**Comment by adambrett** [comment]
Overwriting is a deliberate decision so you don't have to remove then re-add a parameter, you just set a new value.

Maybe after this I could look at adding an `AppendingBuilder` class or something like that.

I'll merge #9 and tag a new release with just this stuff for now, so it should show up in packagist shortly.

**Comment by cvuorinen** [comment]
:+1:
